In [7]:
import pandas as pd
import numpy as np

# Creating persistent randomized values on whole data set
training_all = pd.read_table("/Users/David/Desktop/Zillow/training_all.tsv")
total_rows = training_all.shape[0]
training_all['random_value'] = pd.Series(np.random.randn(total_rows), index=training_all.index)
randomized_training_all = training_all.sort_values(by=['random_value'])
randomized_training_all.to_csv("/Users/David/Desktop/Zillow/randomized_training_all.csv", sep=',', index=False)

# Taking about 10% of superset for training for now
training_sample = randomized_training_all.head(17000)
training_sample.to_csv("/Users/David/Desktop/Zillow/training_sample.csv", sep=',', index=False)

In [11]:
# And about 1% of superset for testing
testing_sample = randomized_training_all.head(18700).tail(1699)
testing_sample.to_csv("/Users/David/Desktop/Zillow/testing_sample.csv", sep=',', index=False)

In [44]:
# training_sample = pd.read_csv('/Users/David/Desktop/Zillow/training_sample.csv')
# training_sample[training_sample.logerror == 0].shape

training_sample[training_sample.logerror == 0]

,parcelid,logerror,transactiondate,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,...,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock,random_value
169,12866859,0.0,2016-12-01,1.0,NaN,NaN,3.0,3.0,NaN,4.0,...,NaN,205205.0,357110.0,2015.0,151905.0,4447.34,NaN,NaN,6.037402e+13,-3.075292
173,12729230,0.0,2016-08-26,NaN,NaN,NaN,3.0,3.0,NaN,4.0,...,NaN,73966.0,274563.0,2015.0,200597.0,3618.25,NaN,NaN,6.037503e+13,-3.064632
246,14070012,0.0,2016-05-19,NaN,NaN,NaN,2.0,4.0,NaN,NaN,...,NaN,90884.0,293033.0,2015.0,202149.0,3544.12,NaN,NaN,6.059099e+13,-2.962839
343,11748695,0.0,2016-06-01,1.0,NaN,NaN,2.0,2.0,NaN,1.0,...,NaN,180000.0,457000.0,2015.0,277000.0,6248.22,NaN,NaN,6.037213e+13,-2.865417
382,14481555,0.0,2016-07-25,NaN,NaN,NaN,2.5,4.0,NaN,NaN,...,NaN,392317.0,874123.0,2015.0,481806.0,9283.36,NaN,NaN,6.059032e+13,-2.835928
409,12641283,0.0,2016-04-19,1.0,NaN,NaN,3.0,3.0,NaN,4.0,...,NaN,227000.0,463000.0,2015.0,236000.0,5696.13,NaN,NaN,6.037295e+13,-2.817910
855,12255753,0.0,2016-05-26,NaN,NaN,NaN,2.0,3.0,NaN,7.0,...,NaN,28335.0,42993.0,2015.0,14658.0,871.54,NaN,NaN,6.037541e+13,-2.575317
1086,14627527,0.0,2016-02-25,NaN,NaN,NaN,2.5,3.0,NaN,NaN,...,NaN,183589.0,504890.0,2015.0,321301.0,7336.10,NaN,NaN,6.059032e+13,-2.490598
1250,10956563,0.0,2016-07-13,NaN,NaN,NaN,2.0,3.0,NaN,7.0,...,NaN,133714.0,564936.0,2015.0,431222.0,6367.75,NaN,NaN,6.037311e+13,-2.435837
1301,12795960,0.0,2016-08-31,NaN,NaN,NaN,1.0,3.0,NaN,7.0,...,NaN,26900.0,59515.0,2015.0,32615.0,962.18,NaN,NaN,6.037502e+13,-2.421777
1313,14667387,0.0,2016-08-16,NaN,NaN,NaN,2.0,2.0,NaN,NaN,...,NaN,101619.0,358000.0,2015.0,256381.0,4770.34,NaN,NaN,6.059076e+13,-2.417976
1421,11653272,0.0,2016-08-11,NaN,NaN,NaN,4.0,4.0,NaN,1.0,...,NaN,187249.0,305547.0,2015.0,118298.0,4195.48,NaN,NaN,6.037261e+13,-2.388541
1758,11222452,0.0,2016-05-04,NaN,NaN,NaN,2.0,3.0,NaN,7.0,...,NaN,73157.0,97193.0,2015.0,24036.0,1305.29,NaN,NaN,6.037911e+13,-2.303263
2155,14441302,0.0,2016-11-09,NaN,NaN,NaN,0.0,0.0,NaN,NaN,...,NaN,225015.0,423579.0,2015.0,198564.0,4383.98,NaN,NaN,6.059042e+13,-2.227703
2170,12682721,0.0,2016-11-04,NaN,NaN,NaN,2.0,3.0,NaN,7.0,...,NaN,87082.0,163970.0,2015.0,76888.0,2153.86,NaN,NaN,6.037651e+13,-2.225836
2430,12336754,0.0,2016-02-24,1.0,NaN,NaN,4.0,4.0,NaN,4.0,...,NaN,268347.0,445966.0,2015.0,177619.0,5593.90,NaN,NaN,6.037551e+13,-2.178399
2459,14207512,0.0,2016-04-20,NaN,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,282227.0,616610.0,2015.0,334383.0,8065.94,NaN,NaN,6.059022e+13,-2.174603
2683,11949807,0.0,2016-09-30,NaN,NaN,NaN,1.0,2.0,NaN,7.0,...,NaN,27913.0,139590.0,2015.0,111677.0,1729.84,NaN,NaN,6.037188e+13,-2.139107
2735,14127546,0.0,2016-04-25,NaN,NaN,NaN,1.0,2.0,NaN,NaN,...,NaN,39694.0,322207.0,2015.0,282513.0,3872.12,NaN,NaN,6.059110e+13,-2.132842
2931,13949886,0.0,2016-09-01,NaN,NaN,NaN,2.5,2.0,NaN,NaN,...,NaN,71435.0,287839.0,2015.0,216404.0,3736.26,NaN,NaN,6.059089e+13,-2.104148
3065,14478665,0.0,2016-05-20,NaN,NaN,NaN,3.0,5.0,NaN,NaN,...,NaN,377223.0,715895.0,2015.0,338672.0,6900.64,NaN,NaN,6.059032e+13,-2.086844
3193,13846735,0.0,2016-08-09,NaN,NaN,NaN,0.0,0.0,NaN,NaN,...,NaN,114287.0,214110.0,2015.0,99823.0,3371.64,NaN,NaN,6.059075e+13,-2.069123
3247,17150684,0.0,2016-06-23,NaN,NaN,NaN,2.0,2.0,NaN,NaN,...,NaN,161399.0,322798.0,2015.0,161399.0,4129.38,NaN,NaN,6.111004e+13,-2.061825
3361,14238673,0.0,2016-07-21,13.0,NaN,NaN,2.5,2.0,NaN,NaN,...,NaN,107770.0,332000.0,2015.0,224230.0,4066.28,NaN,NaN,6.059076e+13,-2.047897
3399,12391958,0.0,2016-10-07,NaN,NaN,NaN,1.0,2.0,NaN,7.0,...,NaN,77150.0,236436.0,2015.0,159286.0,3310.59,NaN,NaN,6.037500e+13,-2.043219
4147,11638411,0.0,2016-03-08,NaN,NaN,NaN,5.0,7.0,NaN,10.0,...,NaN,1100000.0,5500000.0,2015.0,4400000.0,65090.82,NaN,NaN,6.037701e+13,-1.964504
4252,17256139,0.0,2016-08-03,NaN,NaN,NaN,2.0,5.0,NaN,NaN,...,NaN,130389.0,200584.0,2015.0,70195.0,2503.58,NaN,NaN,6.111008e+13,-1.953772
4395,14716356,0.0,2016-02-29,NaN,NaN,NaN,2.5,4.0,NaN,NaN,...,NaN,178586.0,628000.0,2015.0,449414.0,6334.40,NaN,NaN,6.059063e+13,-1.939326
4495,12414589,0.0,2016-10-06,NaN,NaN,NaN,2.0,4.0,NaN,7.0,...,NaN,156546.0,306564.0,2015.0,150018.0,3713.06,NaN,NaN,6.037555e+13,-1.929665
4882,17256107,0.0,2016-05-02,NaN,NaN,NaN,2.0,4.0,NaN,NaN,...,NaN,101644.0,156363.0,2015.0,54719.0,2030.32,NaN,NaN,6.111008e+13,-1.894164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11574,11036284,0.0,2016-12-29,1.0,NaN,NaN,2.0,3.0,NaN,4.0,...,NaN,118694.0,192679.0,2015.0,73985.0,2360.37,NaN,NaN,6.037119e+13,-1.483902
12034,11664563,0.0,2016-02-23,NaN,NaN,NaN,2.0,3.0,NaN,4.0,...,NaN,152420.0,459781.0,2015.0,307361.0,5734.63,NaN,NaN,6.037263e+13,-1.462785
12052,12405861,0.0,2016-07-27,NaN,NaN,NaN,1.0,2.0,NaN,7.0,...,NaN,35860.0,179304.0,2015.0,143444.0,3132.29,NaN,NaN,6.037555e+13,-1.462104
12263,11176038,0.0,2016-07-01,1.0,NaN,NaN,3.0,3.0,NaN,4.0,...,NaN,202000.0,476000.0,2015.0,274000.0,6584.36,NaN,NaN,6.037920e+13,-1.453323
12349,13916082,0.0,2016-09-21,NaN,NaN,NaN,1.5,3.0,NaN,NaN,...,NaN,74953.0,380375.0,2015.0,305422.0,4589.22,NaN,NaN,6.059086e+13,-1.450101
12463,14664202,0.0,2016-09-28,NaN,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,325989.0,762095.0,2015.0,436106.0,8767.66,NaN,NaN,6.059076e+13,-1.445849
12540,13851234,0.0,2016-06-23,NaN,NaN,NaN,2.0,3.0,NaN,NaN,...,NaN,86654.0,444168.0,2015.0,357514.0,5128.12,NaN,NaN,6.059001e+13,-1.443291
12619,11330036,0.0,2016-04-21,1.0,NaN,NaN,2.0,2.0,NaN,7.0,...,NaN,234930.0,239182.0,2015.0,4252.0,5040.74,NaN,NaN,6.037911e+13,-1.440094
12648,10750668,0.0,2016-07-22,1.0,NaN,NaN,3.0,3.0,NaN,4.0,...,NaN,245358.0,553718.0,2015.0,308360.0,8687.56,NaN,NaN,6.037800e+13,-1.438989
12712,12454627,0.0,2016-09-01,NaN,NaN,NaN,1.0,2.0,NaN,7.0,...,NaN,91687.0,255113.0,2015.0,163426.0,3157.17,NaN,NaN,6.037570e+13,-1.436115
13033,17239646,0.0,2016-09-29,NaN,NaN,NaN,1.5,3.0,NaN,NaN,...,NaN,107000.0,307000.0,2015.0,200000.0,3607.58,NaN,NaN,6.111008e+13,-1.421440
13149,14753416,0.0,2016-07-25,NaN,NaN,NaN,2.0,3.0,NaN,NaN,...,NaN,112222.0,362092.0,2015.0,249870.0,3873.62,NaN,NaN,6.059052e+13,-1.416420
13185,14489458,0.0,2016-02-26,NaN,NaN,NaN,2.5,3.0,NaN,NaN,...,NaN,173665.0,609672.0,2015.0,436007.0,6282.24,NaN,NaN,6.059032e+13,-1.415026
13245,12515774,0.0,2016-04-29,NaN,NaN,NaN,2.0,4.0,NaN,7.0,...,NaN,47714.0,85024.0,2015.0,37310.0,1152.23,NaN,NaN,6.037574e+13,-1.412954
13258,11154865,0.0,2016-04-12,1.0,NaN,NaN,2.0,3.0,NaN,7.0,...,NaN,85279.0,106598.0,2015.0,21319.0,1775.37,NaN,NaN,6.037920e+13,-1.412457
13374,13872819,0.0,2016-01-04,NaN,NaN,NaN,2.0,3.0,NaN,NaN,...,NaN,34946.0,55976.0,2015.0,21030.0,5453.90,NaN,NaN,6.059002e+13,-1.408362
13580,14265139,0.0,2016-01-29,NaN,NaN,NaN,2.0,4.0,NaN,NaN,...,NaN,75488.0,229839.0,2015.0,154351.0,2949.30,NaN,NaN,6.059074e+13,-1.400228
14418,12735447,0.0,2016-05-26,1.0,NaN,NaN,3.0,4.0,NaN,4.0,...,NaN,255995.0,577294.0,2015.0,321299.0,7271.33,NaN,NaN,6.037504e+13,-1.366261
14768,12535652,0.0,2016-01-21,NaN,NaN,NaN,4.0,2.0,NaN,7.0,...,NaN,190482.0,474653.0,2015.0,284171.0,6157.22,NaN,NaN,6.037577e+13,-1.353820
15056,14397593,0.0,2016-06-24,NaN,NaN,NaN,2.0,3.0,NaN,NaN,...,NaN,118042.0,679000.0,2015.0,560958.0,6889.72,NaN,NaN,6.059042e+13,-1.342565
15164,11936737,0.0,2016-07-05,1.0,NaN,NaN,2.0,3.0,NaN,4.0,...,NaN,129299.0,198828.0,2015.0,69529.0,2411.94,NaN,NaN,6.037198e+13,-1.338662
15247,14271334,0.0,2016-04-28,NaN,NaN,NaN,2.0,1.0,NaN,NaN,...,NaN,64142.0,365170.0,2015.0,301028.0,4894.34,NaN,NaN,6.059064e+13,-1.336384
15653,12198504,0.0,2016-03-16,NaN,NaN,NaN,1.0,2.0,NaN,7.0,...,NaN,30400.0,108615.0,2015.0,78215.0,2468.81,NaN,NaN,6.037535e+13,-1.321676
15840,14749923,0.0,2016-06-01,NaN,NaN,NaN,1.0,1.0,NaN,NaN,...,NaN,48015.0,160719.0,2015.0,112704.0,1623.90,NaN,NaN,6.059032e+13,-1.314969
15906,10799618,0.0,2016-02-05,1.0,NaN,NaN,3.0,1.0,NaN,4.0,...,NaN,156535.0,326567.0,2015.0,170032.0,4007.38,NaN,NaN,6.037139e+13,-1.312711
16199,12965422,0.0,2016-04-11,NaN,NaN,NaN,1.0,2.0,NaN,7.0,...,NaN,115000.0,615000.0,2015.0,500000.0,837.71,NaN,NaN,6.037431e+13,-1.303486
16305,12804435,0.0,2016-01-15,NaN,NaN,NaN,2.0,3.0,NaN,7.0,...,NaN,89313.0,161754.0,2015.0,72441.0,2266.99,NaN,NaN,6.037501e+13,-1.299738
16502,14670044,0.0,2016-10-01,NaN,NaN,NaN,2.0,2.0,NaN,NaN,...,NaN,111855.0,345773.0,2015.0,233918.0,4293.78,NaN,NaN,6.059022e+13,-1.292934
16738,11264954,0.0,2016-08-01,NaN,NaN,NaN,3.0,3.0,NaN,4.0,...,NaN,282200.0,323000.0,2015.0,40800.0,4845.63,NaN,NaN,6.037901e+13,-1.285572
16956,11883179,0.0,2016-05-06,NaN,NaN,NaN,4.0,5.0,NaN,7.0,...,NaN,387900.0,1300000.0,2015.0,912100.0,15513.69,NaN,NaN,6.037481e+13,-1.277440

In [52]:
training_sample.logerror = training_sample.logerror.replace([0], 0.0000001)
testing_sample.logerror = testing_sample.logerror.replace([0], 0.0000001)

training_sample.to_csv("/Users/David/Desktop/Zillow/training_sample_dezeroed.csv", sep=',', index=False)
testing_sample.to_csv("/Users/David/Desktop/Zillow/testing_sample_dezeroed.csv", sep=',', index=False)

In [82]:
training_sample_select_columns = training_sample[['logerror', 'bathroomcnt', 'bedroomcnt', 'taxvaluedollarcnt', 'transactiondate']]
testing_sample_select_columns = testing_sample[['logerror', 'bathroomcnt', 'bedroomcnt', 'taxvaluedollarcnt', 'transactiondate']]

training_sample_select_columns.to_csv("/Users/David/Desktop/Zillow/training_sample_select_columns.csv", sep=',', index=False)
testing_sample_select_columns.to_csv("/Users/David/Desktop/Zillow/testing_sample_select_columns.csv", sep=',', index=False)

In [83]:
import xgboost as xgb

dtrain = xgb.DMatrix('/Users/David/Desktop/Zillow/training_sample_select_columns.csv?format=csv&label_column=0')
dtest = xgb.DMatrix('/Users/David/Desktop/Zillow/testing_sample_select_columns.csv?format=csv&label_column=0')

param = {'max_depth': 2, 'eta': 1, 'silent': 0, 'objective': 'reg:linear'}

evallist = [(dtest, 'eval'), (dtrain, 'train')]

num_round = 7
bst = xgb.train(param, dtrain, num_round, evallist)

[0]	eval-rmse:0.173737	train-rmse:0.172051
[1]	eval-rmse:0.173873	train-rmse:0.171867
[2]	eval-rmse:0.174012	train-rmse:0.17169
[3]	eval-rmse:0.173934	train-rmse:0.171399
[4]	eval-rmse:0.173932	train-rmse:0.171303
[5]	eval-rmse:0.174399	train-rmse:0.171233
[6]	eval-rmse:0.174638	train-rmse:0.171153

In [84]:
training_sample_select_columns = training_sample[['logerror', 'basementsqft', 'bathroomcnt', 'bedroomcnt', 'calculatedbathnbr', 'threequarterbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet6', 'finishedsquarefeet12', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt']]
testing_sample_select_columns = testing_sample[['logerror', 'basementsqft', 'bathroomcnt', 'bedroomcnt', 'calculatedbathnbr', 'threequarterbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet6', 'finishedsquarefeet12', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt']]

training_sample_select_columns.to_csv("/Users/David/Desktop/Zillow/training_sample_select_columns.csv", sep=',', index=False)
testing_sample_select_columns.to_csv("/Users/David/Desktop/Zillow/testing_sample_select_columns.csv", sep=',', index=False)

In [85]:
import xgboost as xgb

dtrain = xgb.DMatrix('/Users/David/Desktop/Zillow/training_sample_select_columns.csv?format=csv&label_column=0')
dtest = xgb.DMatrix('/Users/David/Desktop/Zillow/testing_sample_select_columns.csv?format=csv&label_column=0')

param = {'max_depth': 2, 'eta': 1, 'silent': 0, 'objective': 'reg:linear'}

evallist = [(dtest, 'eval'), (dtrain, 'train')]

num_round = 7
bst = xgb.train(param, dtrain, num_round, evallist)

[0]	eval-rmse:0.173781	train-rmse:0.171725
[1]	eval-rmse:0.173852	train-rmse:0.171513
[2]	eval-rmse:0.173925	train-rmse:0.170687
[3]	eval-rmse:0.174431	train-rmse:0.170586
[4]	eval-rmse:0.174599	train-rmse:0.170483
[5]	eval-rmse:0.175974	train-rmse:0.170248
[6]	eval-rmse:0.175965	train-rmse:0.170073

In [86]:
training_sample_select_columns = training_sample[['logerror', 'basementsqft', 'bathroomcnt', 'bedroomcnt', 'calculatedbathnbr', 'threequarterbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet6', 'finishedsquarefeet12', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'latitude', 'longitude', 'lotsizesquarefeet', 'numberofstories', 'poolsizesum']]
testing_sample_select_columns = testing_sample[['logerror', 'basementsqft', 'bathroomcnt', 'bedroomcnt', 'calculatedbathnbr', 'threequarterbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet6', 'finishedsquarefeet12', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'latitude', 'longitude', 'lotsizesquarefeet', 'numberofstories', 'poolsizesum']]

training_sample_select_columns.to_csv("/Users/David/Desktop/Zillow/training_sample_select_columns.csv", sep=',', index=False)
testing_sample_select_columns.to_csv("/Users/David/Desktop/Zillow/testing_sample_select_columns.csv", sep=',', index=False)

In [87]:
import xgboost as xgb

dtrain = xgb.DMatrix('/Users/David/Desktop/Zillow/training_sample_select_columns.csv?format=csv&label_column=0')
dtest = xgb.DMatrix('/Users/David/Desktop/Zillow/testing_sample_select_columns.csv?format=csv&label_column=0')

param = {'max_depth': 2, 'eta': 1, 'silent': 0, 'objective': 'reg:linear'}

evallist = [(dtest, 'eval'), (dtrain, 'train')]

num_round = 7
bst = xgb.train(param, dtrain, num_round, evallist)

[0]	eval-rmse:0.173781	train-rmse:0.171725
[1]	eval-rmse:0.174045	train-rmse:0.171458
[2]	eval-rmse:0.174182	train-rmse:0.170422
[3]	eval-rmse:0.174281	train-rmse:0.17028
[4]	eval-rmse:0.174399	train-rmse:0.170159
[5]	eval-rmse:0.1746	train-rmse:0.169835
[6]	eval-rmse:0.174678	train-rmse:0.169017

In [88]:
training_sample_select_columns = training_sample[['logerror', 'basementsqft', 'bathroomcnt', 'bedroomcnt', 'calculatedbathnbr', 'threequarterbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet6', 'finishedsquarefeet12', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'latitude', 'longitude', 'lotsizesquarefeet', 'numberofstories', 'poolsizesum', 'roomcnt', 'unitcnt', 'yardbuildingsqft17', 'yardbuildingsqft26', 'taxvaluedollarcnt', 'structuretaxvaluedollarcnt', 'landtaxvaluedollarcnt', 'taxamount']]
testing_sample_select_columns = testing_sample[['logerror', 'basementsqft', 'bathroomcnt', 'bedroomcnt', 'calculatedbathnbr', 'threequarterbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet6', 'finishedsquarefeet12', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'latitude', 'longitude', 'lotsizesquarefeet', 'numberofstories', 'poolsizesum', 'roomcnt', 'unitcnt', 'yardbuildingsqft17', 'yardbuildingsqft26', 'taxvaluedollarcnt', 'structuretaxvaluedollarcnt', 'landtaxvaluedollarcnt', 'taxamount']]

training_sample_select_columns.to_csv("/Users/David/Desktop/Zillow/training_sample_select_columns.csv", sep=',', index=False)
testing_sample_select_columns.to_csv("/Users/David/Desktop/Zillow/testing_sample_select_columns.csv", sep=',', index=False)

In [90]:
import xgboost as xgb

dtrain = xgb.DMatrix('/Users/David/Desktop/Zillow/training_sample_select_columns.csv?format=csv&label_column=0')
dtest = xgb.DMatrix('/Users/David/Desktop/Zillow/testing_sample_select_columns.csv?format=csv&label_column=0')

param = {'max_depth': 2, 'eta': 1, 'silent': 0, 'objective': 'reg:linear'}

evallist = [(dtest, 'eval'), (dtrain, 'train')]

num_round = 10
bst = xgb.train(param, dtrain, num_round, evallist)

[0]	eval-rmse:0.173769	train-rmse:0.171795
[1]	eval-rmse:0.173927	train-rmse:0.17146
[2]	eval-rmse:0.174162	train-rmse:0.171128
[3]	eval-rmse:0.174204	train-rmse:0.170446
[4]	eval-rmse:0.175882	train-rmse:0.170123
[5]	eval-rmse:0.175927	train-rmse:0.169991
[6]	eval-rmse:0.176821	train-rmse:0.169713
[7]	eval-rmse:0.177002	train-rmse:0.169601
[8]	eval-rmse:0.177688	train-rmse:0.169345
[9]	eval-rmse:0.17735	train-rmse:0.169247

In [2]:
import xgboost as xgb

dtrain = xgb.DMatrix('/Users/David/Desktop/Zillow/training_sample_select_columns.csv?format=csv&label_column=0')
dtest = xgb.DMatrix('/Users/David/Desktop/Zillow/testing_sample_select_columns.csv?format=csv&label_column=0')

param = {'max_depth': 1, 'eta': 1, 'silent': 0, 'objective': 'reg:linear'}

evallist = [(dtest, 'eval'), (dtrain, 'train')]

num_round = 10
bst = xgb.train(param, dtrain, num_round, evallist)

[0]	eval-rmse:0.173547	train-rmse:0.172046
[1]	eval-rmse:0.173498	train-rmse:0.171902
[2]	eval-rmse:0.173501	train-rmse:0.171769
[3]	eval-rmse:0.173692	train-rmse:0.171674
[4]	eval-rmse:0.17369	train-rmse:0.171574
[5]	eval-rmse:0.173922	train-rmse:0.171483
[6]	eval-rmse:0.173986	train-rmse:0.171411
[7]	eval-rmse:0.174192	train-rmse:0.171329
[8]	eval-rmse:0.174217	train-rmse:0.171264
[9]	eval-rmse:0.174481	train-rmse:0.171213

In [122]:
# X, y = training_sample.loc[:, training_sample.columns != 'logerror'], training_sample.logerror
X = training_sample[['basementsqft', 'bathroomcnt', 'bedroomcnt', 'calculatedbathnbr', 'threequarterbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet6', 'finishedsquarefeet12', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'latitude', 'longitude', 'lotsizesquarefeet', 'numberofstories', 'poolsizesum', 'roomcnt', 'unitcnt', 'yardbuildingsqft17', 'yardbuildingsqft26', 'taxvaluedollarcnt', 'structuretaxvaluedollarcnt', 'landtaxvaluedollarcnt', 'taxamount']]
y = training_sample[['logerror']]

from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import KFold

crossvalidation = KFold(n=X.shape[0], n_folds=5, shuffle=True, random_state=1)

In [123]:
from sklearn import tree
for depth in range(1,10):
 tree_classifier = tree.DecisionTreeClassifier(
  max_depth=depth, random_state=0)
 if tree_classifier.fit(X,y).tree_.max_depth < depth:
   break
 score = np.mean(cross_val_score(tree_classifier, X, y,
  scoring='accuracy', cv=crossvalidation, n_jobs=1))
 print (depth,score)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').